name: kellementology
favicon: null
layout_spectrum: 0.8463405289221555
typography_spectrum: 0.74567
title: kellementology
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#000000'
    - '#4d443d'
    - '#79a7c9'
    - '#226c95'
  brandStrength: 0.5
  lightness: 0.6136708369012922
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
